name: Convert

on: push

jobs:
  converter:
    name: Run converter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: fabasoad/yaml-json-xml-converter-action@v1.0.0
        id: yaml2json
        with:
          path: 'bootcamp_info_en.yml'
          from: 'yaml'
          to: 'json'
      - name: Print yaml2json result
        run: echo "${{ steps.yaml2json.outputs.data }}"
